import rulesIndexExport from "./rules-index-export.json";

const additionalOWBRules = {
  "throwing spears": { url: "throwing-spear" },
  halberds: { url: "halberd" },
  "additional hand weapons": {
    url: "two-hand-weapons-additional-hand-weapon",
  },
  "cavalry spears": { url: "cavalry-spear" },
  "repeater handguns": { url: "repeater-handgun" },
  "hand weapons": { url: "hand-weapon" },
  flails: { url: "flail" },
  "plague censers": { url: "plague-censer" },
  "great weapons": { url: "great-weapon" },
  whips: { url: "whip" },
  spears: { url: "spears" },
  "morning stars": { url: "morning-star" },
  blowpipes: { url: "blowpipe" },
  handguns: { url: "handgun" },
  lances: { url: "lance" },
  shortbows: { url: "shortbow" },
  "thrusting spears": { url: "thrusting-spear" },
  javelins: { url: "javelin" },
  longbows: { url: "longbow" },
  pistols: { url: "pistol" },
  "throwing axes": { url: "throwing-axe" },
  hellblades: { url: "hellblade" },
  "repeater pistols": { url: "repeater-pistol" },
  "blackbriar javelins": { url: "blackbriar-javelin" },
  drakeguns: { url: "drakegun" },
  "great hammers": { url: "great-hammer" },
  "brimstone guns": { url: "brimstone-gun" },
  clatterguns: { url: "clattergun" },
  crossbows: { url: "crossbow" },
  "throwing weapons": { url: "throwing-weapons" },
  slings: { url: "sling" },
  blunderbusses: { url: "blunderbuss" },
  "repeater handbows": { url: "repeater-handbow" },
  "repeater crossbows": { url: "repeater-crossbow" },
  "daemons of khorne": { url: "daemon-of-khorne" },
  "daemons of tzeentch": { url: "daemon-of-tzeentch" },
  "daemons of nurgle": { url: "daemon-of-nurgle" },
  "daemons of slaanesh": { url: "daemon-of-slaanesh" },
  "asrai spears": { url: "asrai-spear" },
  "asrai longbows": { url: "asrai-longbow" },
  ironfists: { url: "ironfist" },
  general: { url: "the-general-characters" },
  "moonfire shots": { url: "moonfire-shot" },
  "battle standard bearer": { url: "the-battle-standard" },
  champions: { url: "champions" },
  musician: { url: "musicians" },
  "standard bearer": { url: "standard-bearers" },
  wizard: { url: "wizards" },
  "level 1 wizard": { url: "levels-of-wizardry" },
  "level 2 wizard": { url: "levels-of-wizardry" },
  "level 3 wizard": { url: "levels-of-wizardry" },
  "level 4 wizard": { url: "levels-of-wizardry" },
  "storm call warriors": {
    url: "storm-call",
  },
  "doomseeker dwarfs": {
    url: "doomseeker",
  },
  "armour piercing": {
    url: "armour-piercing",
  },
  "nuln state troops empire": {
    url: "nuln-state-troops",
  },
  "crown of horns beastmen": {
    url: "crown-of-horns-beastmen",
  },
  "crown of horns cathay": {
    url: "crown-of-horns-grand-cathay",
  },
  "engine of the gods renegade": {
    url: "engine-of-the-gods-renegade",
  },
  "crown of antlers beastmen": {
    url: "crown-of-antlers",
  },
  "crown of antlers wood-elf-realms": {
    url: "crown-of-antlers",
  },
  "heavy infantry": { url: "heavy-infantry" },
  "helblaster volley gun weapon": {
    url: "helblaster-volley-gun",
  },
  "helstorm rocket battery weapon": {
    url: "helstorm-rocket-battery",
  },
  // Troop type special rules
  parry: { url: "parry" },
  clumsy: { url: "clumsy" },
  lumbering: { url: "lumbering" },
  "ridden monster": { url: "ridden-monster" },
  thunderstomp: { url: "thunderstomp" },
  insignificant: { url: "insignificant" },
  "no one cares": { url: "no-one-cares" },
  undisciplined: { url: "undisciplined" },
  "steady in the ranks": { url: "steady-in-the-ranks" },
  "press of battle": { url: "press-of-battle" },
  "massed infantry": { url: "massed-infantry" },
  "split profile (cavalry)": { url: "split-profile-cavalry" },
  "cavalry support": { url: "cavalry-support" },
  "split profile (chariots)": { url: "split-profile-chariots" },
  "iron shod wheels": { url: "iron-shod-wheels" },
  "churning wheels": { url: "churning-wheels" },
  "firing platform": { url: "firing-platform" },
  "scythed wheels": { url: "scythed-wheels" },
  "split profile (war machine)": { url: "split-profile-war-machine" },
  "weapon of war": { url: "weapon-of-war" },
  "\"we're not paid to fight\"": { url: "were-not-paid-to-fight" },
};

export const synonyms = {
  "the witch": "suffer not...",
  "the revenant": "suffer not...",
  "the mutant": "suffer not...",
  "the daemon": "suffer not...",
  "spear of kurnous": "the spear of kurnous",
  warbows: "warbow",
  greatbows: "greatbow",
  "chracian great blades": "chracian great blade",
  "swords of hoeth": "sword of hoeth",
  "gromril great axes": "gromril great axe",
  "bows of avelorn": "bow of avelorn",
  "ceremonial halberds": "ceremonial halberd",
  "wolf hammers": "wolf hammer",
  shields: "shield",
  bellower: "bellowers & musicians",
  "revered guardian": "battle standard bearer",
  "patrol leader": "battle standard bearer",
  "sky leader": "battle standard bearer",
  "great cannon": "cannon",
  "repeater bolt thrower": "bolt thrower",
  "bolt thrower": "bolt throwers",
  plagueswords: "plaguesword",
  "steam guns dwarfs": "steam gun dwarfs",
  "har ganeth greatswords": "har ganeth greatsword",
  "dread halberds": "dread halberd",
  fanatics: "fanatic",
  "nasty skulkers": "nasty skulker",
  "leadbelcher guns": "leadbelcher gun",
  "leadbelcher guns renegade": "leadbelcher gun renegade",
  "grimfrost weapons": "grimfrost weapon",
  "tiranoc chariots": "tiranoc chariot",
  "steam tank": "empire steam tank",
  halberds: "halberd",
  polearms: "polearm",
  gyrocopters: "gyrocopter",
  "scout gyrocopters": "scout gyrocopter",
  "marauder chieftain": "champions",
  "marauder horsemaster": "champions",
  "lion guard captain": "champions",
  "chracian captain": "champions",
  "jade officer": "champions",
  "jade lancer officer": "champions",
  boss: "champions",
  marksman: "champions",
  preceptor: "champions",
  seneschal: "champions",
  "skeleton champion": "champions",
  "inner circle preceptor": "champions",
  "doom wolf": "champions",
  "crypt haunter": "champions",
  "crypt ghast": "champions",
  "glade knight": "champions",
  kastellan: "champions",
  sharpshooter: "champions",
  hellwraith: "champions",
  crusher: "champions",
  "demigryph preceptor": "champions",
  "count's champion": "champions",
  vargoyle: "champions",
  lordling: "champions",
  reaver: "champions",
  hag: "champions",
  master: "champions",
  bloodshade: "champions",
  "tower master": "champions",
  "draich master": "champions",
  "wildwood warden": "champions",
  "first knight": "champions",
  "dread knight": "champions",
  bladesinger: "champions",
  "handmaiden of the thorn": "champions",
  "hell knight": "champions",
  plagueridden: "champions",
  "spawn leader": "champions",
  "iridescent horror": "champions",
  "ectoplasmic horror": "champions",
  heartseeker: "champions",
  alluress: "champions",
  "master moulder": "champions",
  sergeant: "champions",
  "veteran sergeant": "champions",
  bloodreaper: "champions",
  nymph: "champions",
  guardian: "champions",
  harbinger: "champions",
  "high sister": "champions",
  groinbiter: "champions",
  snarefinger: "champions",
  "high helm": "champions",
  bloodkine: "champions",
  "gouge-horn": "champions",
  "true-horn": "champions",
  "half-horn": "champions",
  gorehoof: "champions",
  shartak: "champions",
  "maneater captain": "champions",
  thunderfist: "champions",
  "keeper of the flame": "champions",
  nightleader: "champions",
  assassin: "champions",
  greyback: "champions",
  "sea master": "champions",
  "pack leader": "champions",
  "grail guardian": "champions",
  champion: "champions",
  gutlord: "champions",
  desperado: "champions",
  "wild hunter": "champions",
  "wind rider": "champions",
  esquire: "champions",
  elder: "champions",
  "lord's bowmen": "champions",
  "ol' deadeye": "champions",
  "royal champion": "champions",
  sentinel: "champions",
  yeoman: "champions",
  gallant: "champions",
  pyroclaster: "champions",
  villein: "champions",
  paragon: "champions",
  warden: "champions",
  "militia leader": "champions",
  ironbeard: "champions",
  "ripperdactyl champion": "champions",
  prospector: "champions",
  "eternal warden": "champions",
  ironwarden: "champions",
  "prophet of doom": "champions",
  overseer: "champions",
  deathmask: "champions",
  "plague deacon": "champions",
  fangleader: "champions",
  watchmaster: "champions",
  "foe-render": "champions",
  "splice-horn": "champions",
  clawleader: "champions",
  "master of arms": "champions",
  "master of arrows": "champions",
  "tomb captain": "champions",
  "master charioteer": "champions",
  "master of horse": "champions",
  kroxigors: "kroxigor",
  ancient: "champions",
  "venerable ancient": "champions",
  "necropolis captain": "champions",
  "royal clan veteran": "champions",
  "borri forkbeard": "champions",
  headtaker: "champions",
  "skin wolf jarl": "champions",
  "first sword": "champions",
  captain: "champions",
  officer: "champions",
  "veteran officer": "champions",
  commander: "champions",
  "shrine keeper": "champions",
  "boar chariot": "orc boar chariot",
  "wolf chariot": "goblin wolf chariot",
  fireglaives: "fireglaive",
  "warplock jezzails": "warplock jezzails",
  "warplock jezzails skaven": "warplock jezzail",
  "scourgerunner chariots": "scourgerunner chariot",
  "bloodwrack shrines": "bloodwrack shrine",
  "bloodwrack medusas": "bloodwrack medusa",
  "snotling pump wagons": "snotling pump wagon",
  "goblin wolf chariots": "goblin wolf chariot",
  "expeditionary marksman": "expeditionary marksmen",
  "braces of pistols": "brace of pistols",
  "troll magic": "lore of troll magic",
  "nuln veteran state troops": "nuln state troops",
  "empire knights panther": "empire knights",
  "empire knights of the white wolf": "empire knights",
  "empire knights of the fiery heart": "empire knights",
  "empire knights of the blazing sun": "empire knights",
  "empire knights of morr": "empire knights",
  "inner circle knights panther": "inner circle knights",
  "inner circle knights of the white wolf": "inner circle knights",
  "inner circle knights of the fiery heart": "inner circle knights",
  "inner circle knights of the blazing sun": "inner circle knights",
  "inner circle knights of morr": "inner circle knights",
  "demigryph knights panther": "demigryph knights",
  "demigryph knights of the white wolf": "demigryph knights",
  "demigryph knights of the fiery heart": "demigryph knights",
  "demigryph knights of the blazing sun": "demigryph knights",
  "demigryph knights of morr": "demigryph knights",
  "ogre pistols": "ogre pistol",
  "light cannons": "light cannon",
  "bigger choppier axe": "bigger, choppier axe",
  orion: "orion, the king in the woods",
  araloth: "araloth, lord of talsyn",
  kralmaw: "kralmaw, the prophet of ruin",
  ghorros: "ghorros warhoof",
  "primal magic": "lore of primal magic",
  "a tingle in the air": "herdstones",
  "dark sorcery": "herdstones",
  "fearsome edifice": "herdstones",
  "bestial fury beastmen": "herdstones",
  "cathayan lances": "cathayan lance",
  "sky lantern crane guns": "sky lantern crane gun",
  "iron hail guns": "iron hail gun",
};

export const rulesMap = {
  ...rulesIndexExport,
  ...additionalOWBRules,
};
